name: hls
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - affine=2.3.0
  - asciitree=0.3.3
  - attrs=20.3.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - cfitsio=3.470
  - cftime=1.3.0
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cryptography=3.3.1
  - curl=7.71.1
  - expat=2.2.9
  - fasteners=0.14.1
  - fiona=1.8.18
  - freetype=2.10.4
  - freexl=1.0.5
  - gdal=3.1.4
  - geopandas=0.8.1
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - glib=2.66.4
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=67.1
  - idna=2.10
  - jpeg=9d
  - kealib=1.4.14
  - krb5=1.17.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libffi=3.3
  - libgdal=3.1.4
  - libglib=2.66.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mkl=2020.4
  - monotonic=1.5
  - msgpack-python=1.0.2
  - munch=2.5.0
  - netcdf4=1.5.5.1
  - numcodecs=0.7.2
  - numpy=1.19.4
  - openjpeg=2.3.1
  - openssl=1.1.1i
  - pandas=1.2.0
  - pcre=8.44
  - pip=20.3.3
  - pixman=0.40.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - proj=7.1.1
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.5
  - rasterio=1.1.8
  - requests=2.25.1
  - rtree=0.9.7
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snuggs=1.4.7
  - sqlite=3.34.0
  - tiledb=2.1.3
  - tk=8.6.10
  - urllib3=1.26.2
  - wheel=0.36.2
  - xarray=0.16.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - zarr=2.6.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip
  - pip:
    - -r requirements.txt