name: Build Notebook Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup ecr-login
      run: |
        sudo apt update > /dev/null
        sudo apt install amazon-ecr-credential-helper ---yes > /dev/null
        echo '{ "credsStore": "ecr-login" } ' > ~/.docker/config.json

    - name: update jupyter dependencies with repo2docker
      uses: yuvipanda/repo2docker-action@allow-cred-helpers
      with:
        DOCKER_USERNAME: ""
        DOCKER_PASSWORD: ""
        DOCKER_REGISTRY: 783616723547.dkr.ecr.us-west-2.amazonaws.com
        IMAGE_NAME: user-image